### ISSUE TITLE
the problems of fixed model's parameters

### ISSUE THREAD

**Issue by travel-go** [facebookresearch/fairseq-py#140]
Hello,I want to consult you a question a. I want to load the trained model, and also load the model's optim. However, because I added a few layers of network to the original model, it showed some errors that he can't load the previous optim because the length does not match. Then I redefined an optimizer that did not load the model's optimistic data.
There are my problems:
1 I wonder if the optimizer before loading has an effect on training results?
2 What is stored inside the model["optim"]? (I intuitively see the optim "param_groups" inside lr, momentm, weight_decay, there is params, the length of the error is also the params inside the length does not match, but I see it is also full of numbers, may be parameters?).
3 What is "state" in mdoel["optim"]?(I find it is the same number as "param_groups",and It stores some parameters of the same size as the model parameter.)
When you have spare time,I hope you can give me an answer. thank you very much!

**Comment by myleott** [comment]
Each optimizer stores some state (e.g., momentum buffers); for example here's some of the state stored by Adam: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/optim/adam.py#L102-L109.

In fairseq we store whatever the optimizer returns from its `state_dict()`: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/utils.py#L45

When you add additional layers, the problem is that the old optimizer state is sized for the original model, so it can't be loaded directly. You have two choices:
1) Discard the optimizer state and start fresh. This is the easiest option, but in my experience discarding the optimizer state (or switching optimizers) can sometimes cause a brief degredation of performance during training.
2) By default fairseq initializes the optimizer with all model parameters: https://github.com/facebookresearch/fairseq-py/blob/master/fairseq/trainer.py#L41. You may be able to modify this to only optimize the old layers, and then call add_param_group [1] to add the new layers. I haven't tried this yet, but in principle it should work.

[1] http://pytorch.org/docs/master/optim.html?highlight=optimizer#torch.optim.Optimizer.add_param_group

**Comment by travel-go** [comment]
Thank you so much for answering my questions in detail, I learned a lot.
