### ISSUE TITLE
Question about argument "max-token"

### ISSUE THREAD

**Issue by playma** [facebookresearch/fairseq-py#37]
Can anyone tell me what does max-token mean?
Is this the same as vocab-size? Or?

"""
Also note that the batch size is specified in terms of the maximum number of tokens per batch (--max-tokens). You may need to use a smaller value depending on the available GPU memory on your system.
"""

**Comment by xvshiting** [comment]
The max-token I think it refer to the max length of a sentence

**Comment by myleott** [comment]
`--max-tokens` refers to the size of each mini-batch, in terms of the number of tokens.

In other implementations, you may see mini-batches specified in terms of the number of sentences. For example, batch size 64 would mean that each mini-batch has 64 sentences. However, since sentences have different lengths, this means that each mini-batch can contain vastly different numbers of tokens (e.g., bsz 64 with sentences of length 4 will result in a very small mini-batch with only 256 tokens, while a batch with sentences of length 30 would have 1920 tokens). In fairseq-py we explicitly specify the maximum number of tokens in each batch, and then fill the batches with as many sentences as will fit.

**Comment by playma** [comment]
@myleott Very thanks.

**Comment by liyucheng09** [comment]
@myleott Sorry for bothering you. But I am curious about how the number of tokens per batch affects the training process and results. In my view, I think it only makes batches being not average and might lead to unexpected results for checkpoints saved in the middle of one epoch.
