### ISSUE TITLE
Why not using torch.distributed

### ISSUE THREAD

**Issue by Zrachel** [facebookresearch/fairseq-py#92]
I'm exploring to train models on cluster composed of multiple machines. 

My question is, both `torch.distributed` and `torch.multiprocessing` support training on multiple cards, is there any reason to choose the latter one? 

Also looking forward to some advices on cluster training for `fairseq-py`, thank you.

**Comment by myleott** [comment]
When we first built fairseq-py, torch.distributed was very new and did not support NCCL as a backend. Since then, a NCCL backend has recently been added to torch.distributed, and we're actively exploring migrating away from torch.multiprocessing and to torch.distributed (with support for multi-node training). We'll update here when it's ready :)
